name:                iterator4
version:             0.1.0.0
github:              "jiup/iterator4"
license:             BSD3
author:              "Jiupeng Zhang"
maintainer:          "jiupeng.zhang@outlook.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            New project

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jiup/iterator4#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  iterator4-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iterator4

tests:
  iterator4-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iterator4
